### ISSUE TITLE
Expose modes as switches

### ISSUE THREAD

**Issue by Tom2527** [jordanryanmoore/homebridge-scout#55]
### Problem
Arming/disarming a security system in HomeKit using an Automation requires authentication. 

### Solution
Exposing the alarm as a switch would allow full automatic arming/disarming with Automations, for instance when leaving the house. 

The switch should switch between Home/Away or Home/Off. 

### Alternatives
The same could be achieved using IFTTT (which I did before using this Plugin) but for security purposes it would be better to use as few internet services as possible. 

### Additional Context
Apple enforced authentication in Automations for security purposes, but this can easily be circumvented by using Siri.

**Comment by jordanryanmoore** [comment]
My intention for this plug-in has been for the Scout system to be modeled as if it had true first-party HomeKit support. As such, I'm hesitant to implement this feature, particularly since it could also lead to the unintentional compromise of people's physical security.

All that being said, here's how I currently envision the implementation of this request:

* An optional `modeSwitches` configuration setting is added, defaulting to `false`.
* If `modeSwitches` is `true`, the plugin adds a switch accessory for every mode in the Scout location.
* If a mode is enabled, its corresponding switch is `on`. If that mode is disabled or any other mode is enabled, the corresponding switch is `off`.
* Turning on a switch arms the corresponding mode.
* Turning off the switch disarms the corresponding mode.
* In order to disarm any mode, you would need to either identify which switch is on and turn it off or turn off all switches.

Would that meet your needs?

**Comment by Tom2527** [comment]
That’s sounds like the perfect solution.

**Comment by jordanryanmoore** [comment]
In thinking more deeply about this, I’ve discovered some additional complexity. HomeKit switches only offer 2 states (on or off), but Scout modes have 5 (disarmed, arming, armed, triggered, or alarmed).

Assuming one switch per Scout mode, it seems logical that a disarmed mode would be off, while arming, armed, triggered, and alarmed would be on. The trouble is, that leaves no way for HomeKit automations to detect when a mode transitions from any of the on-equivalent states to another on-equivalent state (most notably from armed to triggered or alarmed).

**Comment by jordanryanmoore** [comment]
…unless there is yet another switch that indicates the system is alarming. If you were to manually flip the switch on, I could make it trigger the siren (though it wouldn’t technically be alarming).

**Comment by Tom2527** [comment]
You’re right. The switches I had did not necessarily reflect the actual state the system is in. I only used them to arm/disarm. They might even have been stateless.

**Comment by jordanryanmoore** [comment]
I’ve been considering adding a switch for the siren anyway (#10), so that isn’t a big deal. In fact, I might do that feature first since this one might kind of build on it.

**Comment by jordanryanmoore** [comment]
After more thought, I've decided to reject this feature. It is technically simple to implement; however, I worry that someone could unintentionally and unknowingly reduce their physical security with this feature (no matter how many warnings I might add to the documentation).
