### ISSUE TITLE
Additional armed states are reported as OFF

### ISSUE THREAD

**Issue by Tom2527** [jordanryanmoore/homebridge-scout#56]
### Description
States not mapping to the four HomeKit states (home, away, night, off) are listed as OFF

### Reproduction Steps
1. Additional states in Scout are listed as OFF

### Expected Behavior
These states should be listed as armed as the security system is not OFF. 
Preferably, the use could map multiple states to one HomeKit state in the configuration file. 

### To Do

* [x] Update configuration options.
* [ ] Update configuration documentation.
* [x] Implement support for multi-mapped modes.

**Comment by jordanryanmoore** [comment]
It's a little confusing, but a HomeKit security system itself is never armed — only a security system mode is armed. If the Scout mode doesn't correspond to a mode in HomeKit, there's no mode to mark as armed in the HomeKit security system.

**Comment by jordanryanmoore** [comment]
Okay, this is a little confusing, but here's another attempt at an explanation:

A HomeKit security system isn't represented by a simple `on`/`off` state. The security system has a property that is the target mode that can only be one of `stay`, `away`, `night`, or `off`. You cannot just tell a HomeKit security system to "arm" because it needs to know *which* mode to arm.  In the `homebridge-scout` plugin, you specify how each of these map to your Scout modes. In the case of a Scout mode that isn't associated in your homebridge config, it's ambiguous which mode should be enabled since none of them are correct.

**Comment by jordanryanmoore** [comment]
After further thought, I will say that at least being able to see that the system is armed to a mode you can’t set is better than thinking it isn’t armed at all. I could just allow using a list of mode names in configuration, and HomeKit would set whichever one is first in the list.

**Comment by Tom2527** [comment]
I agree. The easiest implementing would be to map all states to a default one (for instance away). Or let the user configure them. For instance I would map “Vacation” to Away. But “Garden” to Home. 

(why additional modes? For instance In vacation mode motion sensors are armed which cannot be done in away mode as pets may trigger false alarms)

**Comment by jordanryanmoore** [comment]
I’ve been considering adding a switch for the siren anyway (#10), so that isn’t a big deal. In fact, I might do that feature first since this one might kind of build on it.

**Comment by jordanryanmoore** [comment]
So, instead of the `modes` configuration being…

```json
"modes": {
  "stay": "Home",
  "away": "Away",
  "night": "Night"
}
```

…it could be…

```json
"modes": {
  "stay": "Home",
  "away": ["Away", "Vacation"],
  "night": "Night"
}
```

If the Scout armed "Vacation" mode, it would appear as "Away" via HomeKit. If you armed "Away" mode via HomeKit, it would arm Scout as "Away".

**Comment by Tom2527** [comment]
That would be perfect.
